### ISSUE TITLE
Review New Hampshire Zoning Atlas ArcGIS and create recommendations for VTZA

### ISSUE THREAD

**Issue by kefortney** [VERSO-UVM/VT_Zoning_Atlas#112]
This is the overall [landing page](https://www.anselm.edu/about/offices-centers-institutes/centers-institutes/center-ethics-society/nh-zoning-atlas)

This is an ArcGIS Story
[https://storymaps.arcgis.com/stories/410e9b3e818344d7858a043b9a5fe8c7
](https://storymaps.arcgis.com/stories/410e9b3e818344d7858a043b9a5fe8c7
)

This is the ArcGIS Map
[https://experience.arcgis.com/experience/d73b0989434c46528cddeff9865ba4f7/page/Page/?org=ANSELM](https://experience.arcgis.com/experience/d73b0989434c46528cddeff9865ba4f7/page/Page/?org=ANSELM
)

Review both and build out recommendations for building something similar for Vermont version (i.e. what are important story concepts, how is it visualized, what does not work) and write it in a document to be shared with @ZWinigrad @thebestyoshibird and @kefortney

**Comment by draman42** [comment]
I shared it as a Notion document, let me know if you didn't receive it!
