### ISSUE TITLE
Set up Coworking Time

### ISSUE THREAD

**Issue by kefortney** [VERSO-UVM/VT_Zoning_Atlas#89]
Poll your team members and identify two times a week where everyone can jump on a teams call for two hours, set it in the background and work together or ask questions.

Set up these reoccurring meetings
Think about ways to help make them productive in brining the team together, building trust to ask for each other's help and work towards a common goal

**Comment by thebestyoshibird** [comment]
Loop me in on the times you come up with in case anyone from another team ever needs to hop on for a few minutes. Most likely it would be someone from the VHFA/CAS team checking in with Aleah, who will be helping them with their GIS.
