### ISSUE TITLE
Read How to Build a Zoning Atlas (overview + GIS sections)

### ISSUE THREAD

**Issue by thebestyoshibird** [VERSO-UVM/VT_Zoning_Atlas#91]
https://papers.ssrn.com/sol3/papers.cfm?abstract_id=4476927

Tucker/Zach - Just look for changes from prior workflow!

**Comment by thebestyoshibird** [comment]
Aleah - you should definitely read the intro, overview, and GIS chapters. 

Zach & Tucker - even though you've read this already, you should check the new version for updates or clarifications since you started last semester.

**Comment by ZWinigrad** [comment]
I have read the new sections, so Tucker or Aleah can close the issue when they are both done

**Comment by aellwhy** [comment]
I have also just finished reading the sections, so it is set to be closed when Tucker is done.

**Comment by tuckers15** [comment]
I've reviewed the new sections, closing this issue.
